export const icons = {
  menuIcon: {
    dashboard: "/icons/menuIcons/dashboard.svg",
    users: "/icons/menuIcons/users.svg",
    events: "/icons/menuIcons/events.svg",
    safeSpot: "/icons/menuIcons/safespot.svg",
    safeMeet: "/icons/menuIcons/safemeet.svg",
    subscription: "/icons/menuIcons/subscription.svg",
    docsManagement: "/icons/menuIcons/docsManagement.svg",
    list: "/icons/menuIcons/list.svg",
    organiser: "/icons/menuIcons/organiser.svg",
    request: "/icons/menuIcons/request.svg",
  },
  checked: "/icons/checked.svg",
  unChecked: "/icons/unCheck.svg",
  close: "/icons/close.svg",
  logo: "/icons/ufo-logo.svg",
  changePassword: "/icons/change-password.svg",
  tick: "/icons/tick.svg",
  edit: "/icons/edit.svg",
  plusCircular: "/icons/plusCircular.svg",
  chevronDown: "/icons/chevronUp.svg",
  chevronUP: "/icons/chevronDown.svg",
};
