const users = [
    {
      userId: "USR001",
      fullName: "Ravi Kumar",
      email: "ravi.kumar@example.com",
      userImg: "https://example.com/images/user1.jpg",
      phNumber: "+91 9876543210",
      gender: "Male",
      dateOfRegistration: "2025-01-05",
      isSubscribed: true,
      subscriptionType: "Premium",
      status: "Active",
    },
    {
      userId: "USR002",
      fullName: "Aisha Sharma",
      email: "aisha.sharma@example.com",
      userImg: "https://example.com/images/user2.jpg",
      phNumber: "+91 9988776655",
      gender: "Female",
      dateOfRegistration: "2025-01-07",
      isSubscribed: false,
      subscriptionType: "None",
      status: "Active",
    },
    {
      userId: "USR003",
      fullName: "Kunal Verma",
      email: "kunal.verma@example.com",
      userImg: "https://example.com/images/user3.jpg",
      phNumber: "+91 9090909090",
      gender: "Male",
      dateOfRegistration: "2025-01-09",
      isSubscribed: true,
      subscriptionType: "Gold",
      status: "Active",
    },
    {
      userId: "USR004",
      fullName: "Sana Khan",
      email: "sana.khan@example.com",
      userImg: "https://example.com/images/user4.jpg",
      phNumber: "+91 9123456701",
      gender: "Female",
      dateOfRegistration: "2025-01-11",
      isSubscribed: true,
      subscriptionType: "Basic",
      status: "Active",
    },
    {
      userId: "USR005",
      fullName: "Aditya Singh",
      email: "aditya.singh@example.com",
      userImg: "https://example.com/images/user5.jpg",
      phNumber: "+91 9812345678",
      gender: "Male",
      dateOfRegistration: "2025-01-13",
      isSubscribed: false,
      subscriptionType: "None",
      status: "Blocked",
    },
    {
      userId: "USR006",
      fullName: "Priya Nair",
      email: "priya.nair@example.com",
      userImg: "https://example.com/images/user6.jpg",
      phNumber: "+91 9345678901",
      gender: "Female",
      dateOfRegistration: "2025-01-14",
      isSubscribed: true,
      subscriptionType: "Premium",
      status: "Active",
    },
    {
      userId: "USR007",
      fullName: "Rohit Mehta",
      email: "rohit.mehta@example.com",
      userImg: "https://example.com/images/user7.jpg",
      phNumber: "+91 7012345678",
      gender: "Male",
      dateOfRegistration: "2025-01-16",
      isSubscribed: false,
      subscriptionType: "None",
      status: "Inactive",
    },
    {
      userId: "USR008",
      fullName: "Neha Gupta",
      email: "neha.gupta@example.com",
      userImg: "https://example.com/images/user8.jpg",
      phNumber: "+91 8112233445",
      gender: "Female",
      dateOfRegistration: "2025-01-18",
      isSubscribed: true,
      subscriptionType: "Gold",
      status: "Active",
    },
    {
      userId: "USR009",
      fullName: "Arjun Reddy",
      email: "arjun.reddy@example.com",
      userImg: "https://example.com/images/user9.jpg",
      phNumber: "+91 9002233445",
      gender: "Male",
      dateOfRegistration: "2025-01-19",
      isSubscribed: true,
      subscriptionType: "Premium",
      status: "Active",
    },
    {
      userId: "USR010",
      fullName: "Simran Kaur",
      email: "simran.kaur@example.com",
      userImg: "https://example.com/images/user10.jpg",
      phNumber: "+91 7890123456",
      gender: "Female",
      dateOfRegistration: "2025-01-20",
      isSubscribed: false,
      subscriptionType: "None",
      status: "Inactive",
    },
    {
      userId: "USR011",
      fullName: "Manish Patel",
      email: "manish.patel@example.com",
      userImg: "https://example.com/images/user11.jpg",
      phNumber: "+91 8800112233",
      gender: "Male",
      dateOfRegistration: "2025-01-21",
      isSubscribed: true,
      subscriptionType: "Basic",
      status: "Active",
    },
    {
      userId: "USR012",
      fullName: "Shruti Rao",
      email: "shruti.rao@example.com",
      userImg: "https://example.com/images/user12.jpg",
      phNumber: "+91 9445566771",
      gender: "Female",
      dateOfRegistration: "2025-01-22",
      isSubscribed: true,
      subscriptionType: "Premium",
      status: "Active",
    },
    {
      userId: "USR013",
      fullName: "Vikram Joshi",
      email: "vikram.joshi@example.com",
      userImg: "https://example.com/images/user13.jpg",
      phNumber: "+91 9667788990",
      gender: "Male",
      dateOfRegistration: "2025-01-23",
      isSubscribed: false,
      subscriptionType: "None",
      status: "Blocked",
    },
    {
      userId: "USR014",
      fullName: "Isha Malhotra",
      email: "isha.malhotra@example.com",
      userImg: "https://example.com/images/user14.jpg",
      phNumber: "+91 9344556677",
      gender: "Female",
      dateOfRegistration: "2025-01-24",
      isSubscribed: true,
      subscriptionType: "Gold",
      status: "Active",
    },
    {
      userId: "USR015",
      fullName: "Harsh Chauhan",
      email: "harsh.chauhan@example.com",
      userImg: "https://example.com/images/user15.jpg",
      phNumber: "+91 9887766554",
      gender: "Male",
      dateOfRegistration: "2025-01-25",
      isSubscribed: true,
      subscriptionType: "Premium",
      status: "Active",
    },
    {
      userId: "USR016",
      fullName: "Tanvi Soni",
      email: "tanvi.soni@example.com",
      userImg: "https://example.com/images/user16.jpg",
      phNumber: "+91 9001122334",
      gender: "Female",
      dateOfRegistration: "2025-01-26",
      isSubscribed: false,
      subscriptionType: "None",
      status: "Inactive",
    },
    {
      userId: "USR017",
      fullName: "Dhruv Arora",
      email: "dhruv.arora@example.com",
      userImg: "https://example.com/images/user17.jpg",
      phNumber: "+91 8114455667",
      gender: "Male",
      dateOfRegistration: "2025-01-27",
      isSubscribed: true,
      subscriptionType: "Basic",
      status: "Active",
    },
    {
      userId: "USR018",
      fullName: "Meera Kulkarni",
      email: "meera.kulkarni@example.com",
      userImg: "https://example.com/images/user18.jpg",
      phNumber: "+91 7556677889",
      gender: "Female",
      dateOfRegistration: "2025-01-28",
      isSubscribed: true,
      subscriptionType: "Premium",
      status: "Active",
    },
    {
      userId: "USR019",
      fullName: "Kiran Das",
      email: "kiran.das@example.com",
      userImg: "https://example.com/images/user19.jpg",
      phNumber: "+91 7334455661",
      gender: "Male",
      dateOfRegistration: "2025-01-29",
      isSubscribed: false,
      subscriptionType: "None",
      status: "Active",
    },
    {
      userId: "USR020",
      fullName: "Ankita Jain",
      email: "ankita.jain@example.com",
      userImg: "https://example.com/images/user20.jpg",
      phNumber: "+91 7558899001",
      gender: "Female",
      dateOfRegistration: "2025-01-30",
      isSubscribed: true,
      subscriptionType: "Gold",
      status: "Active",
    },
    {
      userId: "USR021",
      fullName: "Sahil Kapoor",
      email: "sahil.kapoor@example.com",
      userImg: "https://example.com/images/user21.jpg",
      phNumber: "+91 7223344556",
      gender: "Male",
      dateOfRegistration: "2025-02-02",
      isSubscribed: true,
      subscriptionType: "Premium",
      status: "Active",
    },
    {
      userId: "USR022",
      fullName: "Ritika Bansal",
      email: "ritika.bansal@example.com",
      userImg: "https://example.com/images/user22.jpg",
      phNumber: "+91 7665522110",
      gender: "Female",
      dateOfRegistration: "2025-02-03",
      isSubscribed: false,
      subscriptionType: "None",
      status: "Inactive",
    },
    {
      userId: "USR023",
      fullName: "Nikhil Roy",
      email: "nikhil.roy@example.com",
      userImg: "https://example.com/images/user23.jpg",
      phNumber: "+91 8111223344",
      gender: "Male",
      dateOfRegistration: "2025-02-04",
      isSubscribed: true,
      subscriptionType: "Basic",
      status: "Active",
    },
    {
      userId: "USR024",
      fullName: "Pooja Shetty",
      email: "pooja.shetty@example.com",
      userImg: "https://example.com/images/user24.jpg",
      phNumber: "+91 8332211009",
      gender: "Female",
      dateOfRegistration: "2025-02-05",
      isSubscribed: true,
      subscriptionType: "Gold",
      status: "Active",
    },
    {
      userId: "USR025",
      fullName: "Aman Yadav",
      email: "aman.yadav@example.com",
      userImg: "https://example.com/images/user25.jpg",
      phNumber: "+91 9110099887",
      gender: "Male",
      dateOfRegistration: "2025-02-06",
      isSubscribed: false,
      subscriptionType: "None",
      status: "Blocked",
    },
    {
      userId: "USR026",
      fullName: "Shreya Sen",
      email: "shreya.sen@example.com",
      userImg: "https://example.com/images/user26.jpg",
      phNumber: "+91 8776654321",
      gender: "Female",
      dateOfRegistration: "2025-02-07",
      isSubscribed: true,
      subscriptionType: "Premium",
      status: "Active",
    },
    {
      userId: "USR027",
      fullName: "Kartik Sharma",
      email: "kartik.sharma@example.com",
      userImg: "https://example.com/images/user27.jpg",
      phNumber: "+91 7009988776",
      gender: "Male",
      dateOfRegistration: "2025-02-08",
      isSubscribed: true,
      subscriptionType: "Basic",
      status: "Active",
    },
    {
      userId: "USR028",
      fullName: "Naina Kapoor",
      email: "naina.kapoor@example.com",
      userImg: "https://example.com/images/user28.jpg",
      phNumber: "+91 8556677880",
      gender: "Female",
      dateOfRegistration: "2025-02-09",
      isSubscribed: false,
      subscriptionType: "None",
      status: "Inactive",
    },
    {
      userId: "USR029",
      fullName: "Rohan Malhotra",
      email: "rohan.malhotra@example.com",
      userImg: "https://example.com/images/user29.jpg",
      phNumber: "+91 9112288330",
      gender: "Male",
      dateOfRegistration: "2025-02-10",
      isSubscribed: true,
      subscriptionType: "Gold",
      status: "Active",
    },
    {
      userId: "USR030",
      fullName: "Divya Pillai",
      email: "divya.pillai@example.com",
      userImg: "https://example.com/images/user30.jpg",
      phNumber: "+91 9445566008",
      gender: "Female",
      dateOfRegistration: "2025-02-11",
      isSubscribed: true,
      subscriptionType: "Premium",
      status: "Active",
    },
  ];
  